title: Studiocraft
author: Bryan Colosky
year: 2016

port: 3001
url: http://studiocraft.cc
baseurl: /

exclude: [package.json, bower.json, Gruntfile.js, node_modules, bower_components, /**/styles, /**/scripts, .bowerrc, .sass-cache, .DS_Store, .gitignore, .editorconfig, .jshintrc, /*.yml, /*.txt, /*.md, /*.ai, /*.pdf, /*.indd, /*.idlk]
